// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZ-LFvnzQ5RhBp6AyUzVzPYs5s9i86GE',
    appId: '1:1032161510153:web:e8298af4f6b3b53558c9d8',
    messagingSenderId: '1032161510153',
    projectId: 'textrecognition-3dd9e',
    authDomain: 'textrecognition-3dd9e.firebaseapp.com',
    storageBucket: 'textrecognition-3dd9e.appspot.com',
    measurementId: 'G-KCD55RJDLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7S-6gmhS8_W7NoBFotpUUJiGEZnh1NJQ',
    appId: '1:1032161510153:android:db07b48a850e61cd58c9d8',
    messagingSenderId: '1032161510153',
    projectId: 'textrecognition-3dd9e',
    storageBucket: 'textrecognition-3dd9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLyK0KOhNg4MoUgR9vKI6KTLDwM9WZYNk',
    appId: '1:1032161510153:ios:d1e0eb4becd0f5ad58c9d8',
    messagingSenderId: '1032161510153',
    projectId: 'textrecognition-3dd9e',
    storageBucket: 'textrecognition-3dd9e.appspot.com',
    iosClientId: '1032161510153-925lc0q5n2qlla9orht8a4f54q8te6k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.textRecognitionProject',
  );
}
